<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTeamSeasonStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('team_season_stats', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('team_id')->nullable();
            $table->foreign('team_id')
                ->references('id')
                ->on('teams')
                ->onDelete('cascade')
                ->onUpdate('cascade');
            $table->binary('SeasonType')->nullable();
            $table->unsignedBigInteger('season_id');
            $table->foreign('season_id')
                ->references('id')
                ->on('seasons')
                ->onDelete('cascade')
                ->onUpdate('cascade');
            $table->text('Name')->nullable();
            $table->text('Team')->nullable();
            $table->integer('Wins')->nullable();
            $table->integer('Losses')->nullable();
            $table->text('OpponentPosition')->nullable();
            $table->float('Possessions')->nullable();
            $table->integer('GlobalTeamID')->nullable();
            $table->text('Updated')->nullable();
            $table->integer('Games')->nullable();
            $table->float('FantasyPoints')->nullable();
            $table->integer('Minutes')->nullable();
            $table->integer('Seconds')->nullable();
            $table->float('FieldGoalsMade')->nullable();
            $table->float('FieldGoalsAttempted')->nullable();
            $table->float('FieldGoalsPercentage')->nullable();
            $table->float('EffectiveFieldGoalsPercentage')->nullable();
            $table->float('TwoPointersMade')->nullable();
            $table->float('TwoPointersAttempted')->nullable();
            $table->float('TwoPointersPercentage')->nullable();
            $table->float('ThreePointersMade')->nullable();
            $table->float('ThreePointersAttempted')->nullable();
            $table->float('ThreePointersPercentage')->nullable();
            $table->float('FreeThrowsMade')->nullable();
            $table->float('FreeThrowsAttempted')->nullable();
            $table->float('FreeThrowsPercentage')->nullable();
            $table->float('OffensiveRebounds')->nullable();
            $table->float('DefensiveRebounds')->nullable();
            $table->float('Rebounds')->nullable();
            $table->float('OffensiveReboundsPercentage')->nullable();
            $table->float('DefensiveReboundsPercentage')->nullable();
            $table->float('TotalReboundsPercentage')->nullable();
            $table->float('Assists')->nullable();
            $table->float('Steals')->nullable();
            $table->float('BlockedShots')->nullable();
            $table->float('Turnovers')->nullable();
            $table->float('PersonalFouls')->nullable();
            $table->float('Points')->nullable();
            $table->float('TrueShootingAttempts')->nullable();
            $table->float('TrueShootingPercentage')->nullable();
            $table->float('PlayerEfficiencyRating')->nullable();
            $table->float('AssistsPercentage')->nullable();
            $table->float('StealsPercentage')->nullable();
            $table->float('BlocksPercentage')->nullable();
            $table->float('TurnOversPercentage')->nullable();
            $table->float('UsageRatePercentage')->nullable();
            $table->float('FantasyPointsFanDuel')->nullable();
            $table->float('FantasyPointsDraftKings')->nullable();
            $table->float('FantasyPointsYahoo')->nullable();
            $table->float('PlusMinus')->nullable();
            $table->float('DoubleDoubles')->nullable();
            $table->float('TripleDoubles')->nullable();
            $table->float('FantasyPointsFantasyDraft')->nullable();
            $table->text('IsClosed')->nullable();
            $table->text('LineupConfirmed')->nullable();
            $table->text('LineupStatus')->nullable();
            $table->unsignedBigInteger('opponent_stat_stat_id')->nullable();
            $table->foreign('opponent_stat_stat_id')
                ->references('id')
                ->on('team_season_stats')
                ->onDelete('cascade')
                ->onUpdate('cascade');
            $table->unsignedBigInteger('opponent_stat_team_id')->nullable();
            $table->foreign('opponent_stat_team_id')
                ->references('id')
                ->on('teams')
                ->onDelete('cascade')
                ->onUpdate('cascade');
            $table->binary('OpponentStatSeasonType')->nullable();
            $table->unsignedBigInteger('opponent_stat_season_id')->nullable();
            $table->foreign('opponent_stat_season_id')
                ->references('id')
                ->on('seasons')
                ->onDelete('cascade')
                ->onUpdate('cascade');
            $table->text('OpponentStatName')->nullable();
            $table->text('OpponentStatTeam')->nullable();
            $table->integer('OpponentStatWins')->nullable();
            $table->integer('OpponentStatLosses')->nullable();
            $table->text('OpponentStatOpponentPosition')->nullable();
            $table->float('OpponentStatPossessions')->nullable();
            $table->integer('OpponentStatGlobalTeamID')->nullable();
            $table->text('OpponentStatUpdated')->nullable();
            $table->integer('OpponentStatGames')->nullable();
            $table->float('OpponentStatFantasyPoints')->nullable();
            $table->integer('OpponentStatMinutes')->nullable();
            $table->integer('OpponentStatSeconds')->nullable();
            $table->float('OpponentStatFieldGoalsMade')->nullable();
            $table->float('OpponentStatFieldGoalsAttempted')->nullable();
            $table->float('OpponentStatFieldGoalsPercentage')->nullable();
            $table->float('OpponentStatEffectiveFieldGoalsPercentage')->nullable();
            $table->float('OpponentStatTwoPointersMade')->nullable();
            $table->float('OpponentStatTwoPointersAttempted')->nullable();
            $table->float('OpponentStatTwoPointersPercentage')->nullable();
            $table->float('OpponentStatThreePointersMade')->nullable();
            $table->float('OpponentStatThreePointersAttempted')->nullable();
            $table->float('OpponentStatThreePointersPercentage')->nullable();
            $table->float('OpponentStatFreeThrowsMade')->nullable();
            $table->float('OpponentStatFreeThrowsAttempted')->nullable();
            $table->float('OpponentStatFreeThrowsPercentage')->nullable();
            $table->float('OpponentStatOffensiveRebounds')->nullable();
            $table->float('OpponentStatDefensiveRebounds')->nullable();
            $table->float('OpponentStatRebounds')->nullable();
            $table->text('OpponentStatOffensiveReboundsPercentage')->nullable();
            $table->text('OpponentStatDefensiveReboundsPercentage')->nullable();
            $table->text('OpponentStatTotalReboundsPercentage')->nullable();
            $table->float('OpponentStatAssists')->nullable();
            $table->float('OpponentStatSteals')->nullable();
            $table->float('OpponentStatBlockedShots')->nullable();
            $table->float('OpponentStatTurnovers')->nullable();
            $table->float('OpponentStatPersonalFouls')->nullable();
            $table->float('OpponentStatPoints')->nullable();
            $table->float('OpponentStatTrueShootingAttempts')->nullable();
            $table->float('OpponentStatTrueShootingPercentage')->nullable();
            $table->text('OpponentStatPlayerEfficiencyRating')->nullable();
            $table->text('OpponentStatAssistsPercentage')->nullable();
            $table->text('OpponentStatStealsPercentage')->nullable();
            $table->text('OpponentStatBlocksPercentage')->nullable();
            $table->text('OpponentStatTurnOversPercentage')->nullable();
            $table->text('OpponentStatUsageRatePercentage')->nullable();
            $table->float('OpponentStatFantasyPointsFanDuel')->nullable();
            $table->float('OpponentStatFantasyPointsDraftKings')->nullable();
            $table->float('OpponentStatFantasyPointsYahoo')->nullable();
            $table->float('OpponentStatPlusMinus')->nullable();
            $table->float('OpponentStatDoubleDoubles')->nullable();
            $table->float('OpponentStatTripleDoubles')->nullable();
            $table->float('OpponentStatFantasyPointsFantasyDraft')->nullable();
            $table->text('OpponentStatIsClosed')->nullable();
            $table->text('OpponentStatLineupConfirmed')->nullable();
            $table->text('OpponentStatLineupStatus')->nullable();
            $table->text('OpponentStatOpponentStat')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('team_season_stats');
    }
}
